### ISSUE TITLE
一个大bug

### ISSUE THREAD

**Issue by littlewhite23333** [ScaxeTeam/Scaxe#1]
你好，sunch233，很抱歉打扰你，
![44d49cae6c0a295cd2b88bffc0d3eb79](https://github.com/ScaxeTeam/Scaxe/assets/115134726/42dc4f07-2822-4a55-9db3-99f5dfd24bcf)
我们在使用此核心时发现了一些bug，出现的时间大约是此次更新后:
更新pocketmine文件夹以后，服务器出现了一些红色字的错误，具体内容如下：
Server thread/CRITICAL > 计算地图“world”时出现错误∶Call to a member function isConnected() on null
堆栈跟踪:
#0 D:\Files\Scaxe-main\src\pocketmine\entity\Mob.php(65): pocketmine\entity\ai\behavior\findFoodBehavior->shouldStart()
#1 D:\Files\Scaxe-main\src\pocketmine\entity\Mob.php(43): pocketmine\entity\Mob->checkBehavior()
#2 D:\Files\Scaxe-main\src\pocketmine\level\Level.php(817): pocketmine\entity\Mob->onUpdate(11999)
#3 D:\Files\Scaxe-main\src\pocketmine\Server.php(2741): pocketmine\level\Level->doTick(11999)
#4 D:\Files\Scaxe-main\src\pocketmine\Server.php(2956): pocketmine\Server->checkTickUpdates(11999, 1688982046.7565)
#5 D:\Files\Scaxe-main\src\pocketmine\Server.php(2635): pocketmine\Server->tick()
#6 D:\Files\Scaxe-main\src\pocketmine\Server.php(2513): pocketmine\Server->tickProcessor()
#7 D:\Files\Scaxe-main\src\pocketmine\Server.php(2090): pocketmine\Server->start()
#8 D:\Files\Scaxe-main\src\pocketmine\PocketMine.php(479): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'D:\\Files\\Scaxe-...', 'D:\\Files\\Scaxe-...', 'D:\\Files\\Scaxe-...', 'unknown')
#9 {main}
当玩家加入服务器时，会卡在生成地形中，并且后台不断重新这些红色的错误提示，导致服务器十分卡顿，玩家超时退出后，这些错误代码又消失了，这就是服务端bug的主要表现，望修复！
——lw服务器后台管理团队

**Comment by Sunch233** [comment]
即将修复
